<?php
/**
 * 全国分站内置城市数据（中文名 + 拼音后缀）
 * 用于「一键导入全国分站」：URL 后缀使用拼音，如 index.php?city=baoding
 * 如需更多城市，按 [城市名, 拼音] 追加即可。
 */
return [
    ['北京', 'beijing'], ['天津', 'tianjin'], ['上海', 'shanghai'], ['重庆', 'chongqing'],
    ['石家庄', 'shijiazhuang'], ['唐山', 'tangshan'], ['邯郸', 'handan'], ['保定', 'baoding'],
    ['秦皇岛', 'qinhuangdao'], ['张家口', 'zhangjiakou'], ['承德', 'chengde'], ['沧州', 'cangzhou'],
    ['廊坊', 'langfang'], ['衡水', 'hengshui'], ['太原', 'taiyuan'], ['大同', 'datong'],
    ['阳泉', 'yangquan'], ['长治', 'changzhi'], ['晋城', 'jincheng'], ['晋中', 'jinzhong'],
    ['运城', 'yuncheng'], ['忻州', 'xinzhou'], ['临汾', 'linfen'], ['吕梁', 'lvliang'],
    ['呼和浩特', 'huhehaote'], ['包头', 'baotou'], ['乌海', 'wuhai'], ['赤峰', 'chifeng'],
    ['通辽', 'tongliao'], ['鄂尔多斯', 'eerduosi'], ['呼伦贝尔', 'hulunbeier'], ['巴彦淖尔', 'bayannaoer'],
    ['沈阳', 'shenyang'], ['大连', 'dalian'], ['鞍山', 'anshan'], ['抚顺', 'fushun'],
    ['本溪', 'benxi'], ['丹东', 'dandong'], ['锦州', 'jinzhou'], ['营口', 'yingkou'],
    ['阜新', 'fuxin'], ['辽阳', 'liaoyang'], ['盘锦', 'panjin'], ['铁岭', 'tieling'],
    ['朝阳', 'chaoyang'], ['葫芦岛', 'huludao'], ['长春', 'changchun'], ['吉林', 'jilin'],
    ['四平', 'siping'], ['辽源', 'liaoyuan'], ['通化', 'tonghua'], ['白山', 'baishan'],
    ['松原', 'songyuan'], ['白城', 'baicheng'], ['延边', 'yanbian'], ['哈尔滨', 'haerbin'],
    ['齐齐哈尔', 'qiqihaer'], ['鸡西', 'jixi'], ['鹤岗', 'hegang'], ['双鸭山', 'shuangyashan'],
    ['大庆', 'daqing'], ['伊春', 'yichun'], ['佳木斯', 'jiamusi'], ['七台河', 'qitaihe'],
    ['牡丹江', 'mudanjiang'], ['黑河', 'heihe'], ['绥化', 'suihua'], ['南京', 'nanjing'],
    ['无锡', 'wuxi'], ['徐州', 'xuzhou'], ['常州', 'changzhou'], ['苏州', 'suzhou'],
    ['南通', 'nantong'], ['连云港', 'lianyungang'], ['淮安', 'huaian'], ['盐城', 'yancheng'],
    ['扬州', 'yangzhou'], ['镇江', 'zhenjiang'], ['泰州', 'taizhou'], ['宿迁', 'suqian'],
    ['杭州', 'hangzhou'], ['宁波', 'ningbo'], ['温州', 'wenzhou'], ['嘉兴', 'jiaxing'],
    ['湖州', 'huzhou'], ['绍兴', 'shaoxing'], ['金华', 'jinhua'], ['衢州', 'quzhou'],
    ['舟山', 'zhoushan'], ['台州', 'taizhou2'], ['丽水', 'lishui'], ['合肥', 'hefei'],
    ['芜湖', 'wuhu'], ['蚌埠', 'bengbu'], ['淮南', 'huainan'], ['马鞍山', 'maanshan'],
    ['淮北', 'huaibei'], ['铜陵', 'tongling'], ['安庆', 'anqing'], ['黄山', 'huangshan'],
    ['滁州', 'chuzhou'], ['阜阳', 'fuyang'], ['宿州', 'suzhou2'], ['六安', 'luan'],
    ['亳州', 'bozhou'], ['池州', 'chizhou'], ['宣城', 'xuancheng'], ['福州', 'fuzhou'],
    ['厦门', 'xiamen'], ['莆田', 'putian'], ['三明', 'sanming'], ['泉州', 'quanzhou'],
    ['漳州', 'zhangzhou'], ['南平', 'nanping'], ['龙岩', 'longyan'], ['宁德', 'ningde'],
    ['南昌', 'nanchang'], ['景德镇', 'jingdezhen'], ['萍乡', 'pingxiang'], ['九江', 'jiujiang'],
    ['新余', 'xinyu'], ['鹰潭', 'yingtan'], ['赣州', 'ganzhou'], ['吉安', 'jian'],
    ['宜春', 'yichun2'], ['抚州', 'fuzhou2'], ['上饶', 'shangrao'], ['济南', 'jinan'],
    ['青岛', 'qingdao'], ['淄博', 'zibo'], ['枣庄', 'zaozhuang'], ['东营', 'dongying'],
    ['烟台', 'yantai'], ['潍坊', 'weifang'], ['济宁', 'jining'], ['泰安', 'taian'],
    ['威海', 'weihai'], ['日照', 'rizhao'], ['临沂', 'linyi'], ['德州', 'dezhou'],
    ['聊城', 'liaocheng'], ['滨州', 'binzhou'], ['菏泽', 'heze'], ['郑州', 'zhengzhou'],
    ['开封', 'kaifeng'], ['洛阳', 'luoyang'], ['平顶山', 'pingdingshan'], ['安阳', 'anyang'],
    ['鹤壁', 'hebi'], ['新乡', 'xinxiang'], ['焦作', 'jiaozuo'], ['濮阳', 'puyang'],
    ['许昌', 'xuchang'], ['漯河', 'luohe'], ['三门峡', 'sanmenxia'], ['南阳', 'nanyang'],
    ['商丘', 'shangqiu'], ['信阳', 'xinyang'], ['周口', 'zhoukou'], ['驻马店', 'zhumadian'],
    ['武汉', 'wuhan'], ['黄石', 'huangshi'], ['十堰', 'shiyan'], ['宜昌', 'yichang'],
    ['襄阳', 'xiangyang'], ['鄂州', 'ezhou'], ['荆门', 'jingmen'], ['孝感', 'xiaogan'],
    ['荆州', 'jingzhou'], ['黄冈', 'huanggang'], ['咸宁', 'xianning'], ['随州', 'suizhou'],
    ['长沙', 'changsha'], ['株洲', 'zhuzhou'], ['湘潭', 'xiangtan'], ['衡阳', 'hengyang'],
    ['邵阳', 'shaoyang'], ['岳阳', 'yueyang'], ['常德', 'changde'], ['张家界', 'zhangjiajie'],
    ['益阳', 'yiyang'], ['郴州', 'chenzhou'], ['永州', 'yongzhou'], ['怀化', 'huaihua'],
    ['娄底', 'loudi'], ['广州', 'guangzhou'], ['韶关', 'shaoguan'], ['深圳', 'shenzhen'],
    ['珠海', 'zhuhai'], ['汕头', 'shantou'], ['佛山', 'foshan'], ['江门', 'jiangmen'],
    ['湛江', 'zhanjiang'], ['茂名', 'maoming'], ['肇庆', 'zhaoqing'], ['惠州', 'huizhou'],
    ['梅州', 'meizhou'], ['汕尾', 'shanwei'], ['河源', 'heyuan'], ['阳江', 'yangjiang'],
    ['清远', 'qingyuan'], ['东莞', 'dongguan'], ['中山', 'zhongshan'], ['潮州', 'chaozhou'],
    ['揭阳', 'jieyang'], ['云浮', 'yunfu'], ['南宁', 'nanning'], ['柳州', 'liuzhou'],
    ['桂林', 'guilin'], ['梧州', 'wuzhou'], ['北海', 'beihai'], ['防城港', 'fangchenggang'],
    ['钦州', 'qinzhou'], ['贵港', 'guigang'], ['玉林', 'yulin'], ['百色', 'baise'],
    ['贺州', 'hezhou'], ['河池', 'hechi'], ['来宾', 'laibin'], ['崇左', 'chongzuo'],
    ['海口', 'haikou'], ['三亚', 'sanya'], ['三沙', 'sansha'], ['儋州', 'danzhou'],
    ['成都', 'chengdu'], ['自贡', 'zigong'], ['攀枝花', 'panzhihua'], ['泸州', 'luzhou'],
    ['德阳', 'deyang'], ['绵阳', 'mianyang'], ['广元', 'guangyuan'], ['遂宁', 'suining'],
    ['内江', 'neijiang'], ['乐山', 'leshan'], ['南充', 'nanchong'], ['眉山', 'meishan'],
    ['宜宾', 'yibin'], ['广安', 'guangan'], ['达州', 'dazhou'], ['雅安', 'yaan'],
    ['巴中', 'bazhong'], ['资阳', 'ziyang'], ['贵阳', 'guiyang'], ['六盘水', 'liupanshui'],
    ['遵义', 'zunyi'], ['安顺', 'anshun'], ['毕节', 'bijie'], ['铜仁', 'tongren'],
    ['昆明', 'kunming'], ['曲靖', 'qujing'], ['玉溪', 'yuxi'], ['保山', 'baoshan'],
    ['昭通', 'zhaotong'], ['丽江', 'lijiang'], ['普洱', 'puer'], ['临沧', 'lincang'],
    ['拉萨', 'lasa'], ['日喀则', 'rikaze'], ['昌都', 'changdu'], ['林芝', 'linzhi'],
    ['西安', 'xian'], ['铜川', 'tongchuan'], ['宝鸡', 'baoji'], ['咸阳', 'xianyang'],
    ['渭南', 'weinan'], ['延安', 'yanan'], ['汉中', 'hanzhong'], ['榆林', 'yulin2'],
    ['安康', 'ankang'], ['商洛', 'shangluo'], ['兰州', 'lanzhou'], ['嘉峪关', 'jiayuguan'],
    ['金昌', 'jinchang'], ['白银', 'baiyin'], ['天水', 'tianshui'], ['武威', 'wuwei'],
    ['张掖', 'zhangye'], ['平凉', 'pingliang'], ['酒泉', 'jiuquan'], ['庆阳', 'qingyang'],
    ['定西', 'dingxi'], ['陇南', 'longnan'], ['西宁', 'xining'], ['海东', 'haidong'],
    ['银川', 'yinchuan'], ['石嘴山', 'shizuishan'], ['吴忠', 'wuzhong'], ['固原', 'guyuan'],
    ['中卫', 'zhongwei'], ['乌鲁木齐', 'wulumuqi'], ['克拉玛依', 'kelamayi'], ['吐鲁番', 'tulufan'],
    ['哈密', 'hami'], ['昌吉', 'changji'], ['库尔勒', 'kuerle'], ['阿克苏', 'akesu'],
    ['喀什', 'kashi'], ['伊宁', 'yining'], ['台湾', 'taiwan'], ['香港', 'hongkong'], ['澳门', 'macau'],
];
